input('Nama                 :')
input('NIM                  :')
input('Kelas Paralel        :')
input('Tempat/Tanggal lahir :')
input('Alamat               :')
input('Hobby                :')
input('No.HP                :')